### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by lonnietc** [TTFH/Voxel-Render#1]
Hello,

I am very interested in voxels and there seems to be some suggestion that "voxel rasterization" can significantly speed up rendering to  approximately constant-time rendering and I would like to investigate that more.

But, before digging into the code more, I would like to see your Voxel Render in action and was wondering if you have a Windows (x64) version that I could download and test?

Thanks

**Comment by TTFH** [comment]
I just released a build for Windows.
Keep in mind that this project is something I did in a pair of weeks while I was bored, performance is quite bad.

**Comment by lonnietc** [comment]
Thanks for the release and I will look at it more now.

Mostly I want to learn since I am working towards building a new type of voxel engine and want to research various methods and techniques that might be integrated into it.
