### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by SamoZ256** [TTFH/Voxel-Render#2]
Are there any plans to support MacOS in the future? I'm pretty interested in running it on my computer

**Comment by TTFH** [comment]
I don't have a MacOS device, so there is no way for me to test it.
However you should be able to compile it in MacOS, first you need to install GLFW with the next command: `brew install glfw`

And add the next code to `Makefile` under _BUILD FLAGS PER PLATFORM_
```
ifeq ($(UNAME_S), Darwin) #APPLE
	ECHO_MESSAGE = "Mac OS X"
        CXXFLAGS += -Wno-unused-result
	LIBS += -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo
	LIBS += -L/usr/local/lib -L/opt/local/lib -L/opt/homebrew/lib
	LIBS += -lglfw
	CXXFLAGS += -I/usr/local/include -I/opt/local/include -I/opt/homebrew/include
endif
```
[example makefile from imgui](https://github.com/ocornut/imgui/blob/master/examples/example_glfw_opengl3/Makefile)

**Comment by SamoZ256** [comment]
I managed to run it on MacOS. There are 3 main issues:
1. The performance isn't good (around 90 ms on 7-core M1 MacBook Air).
2. The viewport size is two times smaller than it should be. That's because on some display, window width/height isn't the same as framebuffer width/height.
3. I had to change the version of OpenGL to 4.1, since that's the maximum Apple supports.

Aside from that, would you accept such pull request?

**Comment by SamoZ256** [comment]
Actually, the performance of the example is good (8 ms). I was testing the castle example before

**Comment by TTFH** [comment]
#3 was merged.
