### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by jackcrane** [TTFH/Voxel-Render#9]
Hello,

I am unable to build this using `make`, is it possible to have you upload a compiled binary to a release?

Thanks!

**Comment by TTFH** [comment]
I'll update this project when I get some free time and upload a new build, I was working on a refactoring but that was paused for some weeks.

**Comment by jackcrane** [comment]
I understand the level of personal challenge with maintaining open source projects like this especially for free. Do you have a buymeacoffee or patreon I can contribute to to help justify your time to upload the new build? I have a project that is relatively dependent on this project and am hoping to get it done as soon as possible so would be completely happy with helping to offset the opportunity cost

**Comment by TTFH** [comment]
You can support this project by making a donation to my PayPal account, associated to the email  `ttfh3500@gmail.com`

**Comment by TTFH** [comment]
Added a new release with a compiled binary for Windows.

It includes an example map, but others scenes can be open from the same executable.

For example, download the source, extract castle.7z and copy the folder example/, and the files castle.vox and main.xml, then run `vox_render example/` or `vox_render main.xml`

**Comment by jackcrane** [comment]
I was following the directions to pipe this into Blender, but it does not seem like this bundle has the blender import util, and it also appears that it does not generate the scene and palette. Do you have any recommendations?

**Comment by TTFH** [comment]
Added the executable for Blender export.
https://github.com/TTFH/Voxel-Render/releases/tag/r01

**Comment by jackcrane** [comment]
I attempted to compress the Lee Chemicals map from Teardown and it rendered fine in Voxel Render but when I exported it, it is missing a ton of stuff in Blender. Have you seen something like this happening?


[lee.blend.zip](https://github.com/user-attachments/files/17834945/lee.blend.zip)
[full project (1.5gb)](https://utfs.io/f/xY2vAOTAOWEGqXcVgiDl49hVnY0Q5ZdBkobvaILSH62Ofrwq)

**Comment by TTFH** [comment]
There is some code in the file `blender_import_obj.py`, that limits it to 100 objects/files.
The reason is because it may take a very long time to import the scene.
You can remove:
`    if i % 100 == 0:
        break`
